---
version: "3"

services:
  pihole:
    container_name: pihole
    build:
      dockerfile: ./Dockerfile
      args:
        PIHOELE_DOCKER_TAG: 2023.03.1

    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - ${PIHOLE_WEBPORT:-80}:80/tcp

    environment:
      DNSSEC: true
      DNSMASQ_LISTENING: single
      PIHOLE_DNS_: 127.0.0.1#5335

      TZ: ${PIHOLE_TZ:-Europe/Berlin}
      WEBTHEME: ${WEBTHEME:-default-dark}
      FTLCONF_LOCAL_IPV4: ${FTLCONF_LOCAL_IPV4}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD:-pihole}

    volumes:
      - "etc-pihole:/etc/pihole"
      - "etc-dnsmasq:/etc/dnsmasq.d"

    restart: unless-stopped

volumes:
  etc-pihole:
  etc-dnsmasq:
